services:
  aws-ecr-token-refresher:
    image: docker.io/karimz1/aws-ecr-token-refresher:latest
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID:     ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION:            ${AWS_REGION}
      INTERVAL_SECONDS:      ${INTERVAL_SECONDS}
    volumes:
      # write credentials here ⤵
      - ${HOME}/.docker:/root/.docker
      # talk to the host Docker daemon
      - /var/run/docker.sock:/var/run/docker.sock