name: Deployment for aws-ecr-token-refresher to Docker Hub

on:
 push:
    branches:
      - main
      - development
 repository_dispatch:
    types: [ deploy ]

jobs:
  deploy-image-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Define Tags
        id: define-tags
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "ADDITIONAL_TAG=karimz1/aws-ecr-token-refresher:latest" >> $GITHUB_ENV
          else
            echo "ADDITIONAL_TAG=karimz1/aws-ecr-token-refresher:beta" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.ADDITIONAL_TAG }}

  update-dockerhub-description:
    needs: deploy-image-to-dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Update Docker Hub Description
        run: |
          python ./devops/update_dockerhub_description.py \
              --readme ../ReadMe.md \
              --branch "${{ github.ref }}" \
              --base-url "https://raw.githubusercontent.com/karimz1/aws-ecr-token-refresher/main"
        env:
          DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_REPO: "aws-ecr-token-refresher"